import type { LabTestPlanEntry } from "./types";

export const EVENTBRITE_SKILL_FORGE_PLAN: ReadonlyArray<LabTestPlanEntry> =
  Object.freeze([
    {
      id: "ebf-01",
      provider: "eventbrite",
      intended_class: "eventbrite_event",
      url: "https://www.eventbrite.com/e/quad-state-wine-music-fest-2026-tickets-1965939467870",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Exact Eventbrite event URL should proceed only to a ticket/registration or payment boundary.",
    },
    {
      id: "ebf-02",
      provider: "eventbrite",
      intended_class: "eventbrite_event",
      url: "https://www.eventbrite.com/e/set-piece-comedy-show-tickets-1981445237043",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Exact comedy event URL should safely stop at registration, login, payment, or final-confirm boundary.",
    },
    {
      id: "ebf-03",
      provider: "eventbrite",
      intended_class: "eventbrite_event",
      url: "https://www.eventbrite.com/e/2026-nashville-arts-crafts-vendor-festival-tickets-1984148678108",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Multi-day festival page should remain an exact Eventbrite event and stop before irreversible action.",
    },
    {
      id: "ebf-04",
      provider: "eventbrite",
      intended_class: "eventbrite_event",
      url: "https://www.eventbrite.com/e/writerfest-nashville-2026-tickets-1984649586338",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Conference-style Eventbrite event should expose a safe registration boundary with evidence.",
    },
    {
      id: "ebf-05",
      provider: "eventbrite",
      intended_class: "eventbrite_event",
      url: "https://www.eventbrite.com/e/2026-nashville-pride-festival-tickets-1982228226987",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "High-level festival event should not be treated as a listing or search page.",
    },
    {
      id: "ebf-06",
      provider: "eventbrite",
      intended_class: "eventbrite_event",
      url: "https://www.eventbrite.com/e/free-comedy-show-tickets-stand-up-comedy-greenwich-village-comedy-club-tickets-1983090042701",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Recurring/free ticket event should still hard-stop at user registration or checkout boundary.",
    },
    {
      id: "ebf-07",
      provider: "eventbrite",
      intended_class: "eventbrite_listing",
      url: "https://www.eventbrite.com/d/ny--new-york/comedy--events/",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "City/category comedy listing should collect visible candidate events and ask the user to choose.",
    },
    {
      id: "ebf-08",
      provider: "eventbrite",
      intended_class: "eventbrite_listing",
      url: "https://www.eventbrite.com/d/tn--nashville/music--events/",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "City/category listing should not auto-pick an event; it should surface candidate choices.",
    },
    {
      id: "ebf-09",
      provider: "eventbrite",
      intended_class: "eventbrite_listing",
      url: "https://www.eventbrite.com/d/online/events/",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Online events listing should stay in the user-choice lane.",
    },
    {
      id: "ebf-10",
      provider: "eventbrite",
      intended_class: "eventbrite_directory",
      url: "https://www.eventbrite.com/b/online/",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Generic Eventbrite directory should collect candidates or degrade with evidence, never direct execute.",
    },
  ]);

export const EVENTBRITE_SKILL_FORGE_PLAN_COUNTS = Object.freeze({
  total: EVENTBRITE_SKILL_FORGE_PLAN.length,
  eventbrite: EVENTBRITE_SKILL_FORGE_PLAN.length,
});
