import type { LabTestPlanEntry } from "./types";

export const STUBHUB_SKILL_FORGE_PLAN: ReadonlyArray<LabTestPlanEntry> =
  Object.freeze([
    {
      id: "shf-01",
      provider: "stubhub",
      intended_class: "stubhub_performer",
      url: "https://www.stubhub.com/athletics-tickets/performer/198",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Performer page should surface upcoming Athletics event choices without treating the page as exact event evidence.",
    },
    {
      id: "shf-02",
      provider: "stubhub",
      intended_class: "stubhub_category",
      url: "https://www.stubhub.com/folk-tickets/category/1502307",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Category page should collect visible candidate events and ask the user to choose.",
    },
    {
      id: "shf-03",
      provider: "stubhub",
      intended_class: "stubhub_category",
      url: "https://www.stubhub.com/comedy-tickets/category/209",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Broad comedy category listing should remain a user-choice provider-start page.",
    },
    {
      id: "shf-04",
      provider: "stubhub",
      intended_class: "stubhub_geography",
      url: "https://www.stubhub.com/new-york-metro-tickets/geography/664/",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Geography listing should not pick a ticket automatically; it should collect candidate evidence.",
    },
    {
      id: "shf-05",
      provider: "stubhub",
      intended_class: "stubhub_event",
      url: "https://www.stubhub.com/athletics-sacramento-tickets-5-14-2026/event/159263858/?backUrl=%2Fathletics-tickets%2Fperformer%2F198&lt=38.5810606&lg=-121.493895&bd=true&quantity=2",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Exact event page with query parameters should proceed only to a safe handoff or seat/payment boundary.",
    },
    {
      id: "shf-06",
      provider: "stubhub",
      intended_class: "stubhub_performer",
      url: "https://www.stubhub.com/steve-earle-tickets/performer/828",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Music performer page should use rendered StubHub listings as source of truth.",
    },
    {
      id: "shf-07",
      provider: "stubhub",
      intended_class: "stubhub_event",
      url: "https://www.stubhub.com/steve-earle-chattanooga-tickets-5-24-2026/event/160915354/?backUrl=%2Fsteve-earle-tickets%2Fperformer%2F828&lt=36.13954&lg=-86.8136602&quantity=2",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Exact concert event should safely stop at ticket selection, login, checkout, or payment boundary.",
    },
    {
      id: "shf-08",
      provider: "stubhub",
      intended_class: "stubhub_event",
      url: "https://www.stubhub.com/john-mulaney-nashville-tickets-6-12-2026/event/160512394/",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Exact comedy event URL should never be replaced by search; it should reach a safe ticket boundary or degrade with evidence.",
    },
    {
      id: "shf-09",
      provider: "stubhub",
      intended_class: "stubhub_checkout",
      url: "https://checkout.stubhub.com/secure/buy/checkout?ID=d045373b-46cb-4b2c-adb8-185255e52d55%7c12631332481%7c2%7c0",
      expected_resolver_page_type: "unknown_provider_page",
      expected_resolver_execution_mode: "review_capture",
      reason: "Checkout URL is an explicit payment boundary and must hard-stop without clicking, typing, login, or final purchase.",
    },
    {
      id: "shf-10",
      provider: "stubhub",
      intended_class: "stubhub_event",
      url: "https://www.stubhub.com/world-cup-east-rutherford-tickets-6-16-2026/event/153022598/?quantity=2",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "High-demand exact sports event should stop at seat or payment boundary with screenshot evidence.",
    },
  ]);

export const STUBHUB_SKILL_FORGE_PLAN_COUNTS = Object.freeze({
  total: STUBHUB_SKILL_FORGE_PLAN.length,
  stubhub: STUBHUB_SKILL_FORGE_PLAN.length,
});
