import type { LabTestPlanEntry } from "./types";

/**
 * Ticketmaster Skill Forge seed plan.
 *
 * This is broader than the original 10 Ticketmaster entries in
 * STAGE0B_TEST_PLAN. It intentionally mixes artist, exact event, search,
 * category/listing, and venue-shaped URLs so the controlled Browser Harness
 * lab can learn which surfaces are stable, which need user choice, and which
 * are provider-degraded before any production skill change lands.
 */
export const TICKETMASTER_SKILL_FORGE_PLAN: ReadonlyArray<LabTestPlanEntry> =
  Object.freeze([
    {
      id: "tmf-01",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.com/kacey-musgraves-tickets/artist/1668663?ac_link=ntm_kaceymusgraves26-1_spotlight_1",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Founder-listed artist page with referral query; should extract multiple visible events and ask user choice.",
    },
    {
      id: "tmf-02",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.com/foster-the-people-tickets/artist/1478293?ac_link=NTM_FosterThePeople26-1_spotlight_1",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Founder-listed artist page for a smaller tour; should not claim exact event without a selected date.",
    },
    {
      id: "tmf-03",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.com/westminster-kennel-club-dog-show-tickets/artist/847597",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Annual event-like artist surface; lab should distinguish one candidate from many.",
    },
    {
      id: "tmf-04",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.com/monster-jam-tickets/artist/1542376",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Multi-city family/sports tour; should usually ask user for city/date.",
    },
    {
      id: "tmf-05",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.com/disney-on-ice-presents-find-your-tickets/artist/1742147",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Founder dogfood URL that previously advanced without asking date/time; must ask choice on multiple events.",
    },
    {
      id: "tmf-06",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.com/lil-wayne-tickets/artist/712214?ac_link=ursa_84359098-9ebf-4cbc-a046-9d852562c3bd_a_712214?ac_link=iccp_hp_t3_fallback_K8vZ917GemV",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Founder dogfood URL with double query marker; must preserve URL and ask user choice if multiple events exist.",
    },
    {
      id: "tmf-07",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.com/sabrina-carpenter-tickets/artist/2932128?ac_link=ursa_sabrina",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "High-traffic artist page; should handle long candidate lists without picking silently.",
    },
    {
      id: "tmf-08",
      provider: "ticketmaster",
      intended_class: "ticketmaster_event",
      url: "https://www.ticketmaster.com/nashville-sc-v-dc-united-eddi-nashville-tennessee-05-09-2026/event/1B0063739937BB85",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Founder-provided valid Ticketmaster exact event URL; should reach safe handoff or a known hard stop.",
    },
    {
      id: "tmf-09",
      provider: "ticketmaster",
      intended_class: "ticketmaster_event",
      url: "https://www.ticketmaster.com/kacey-musgraves-middle-of-nowhere-tour-chicago-08-21-2026/event/04006495DF42EC43",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Official Ticketmaster exact event URL discovered from Ticketmaster search index; should not require user choice.",
    },
    {
      id: "tmf-10",
      provider: "ticketmaster",
      intended_class: "ticketmaster_event",
      url: "https://www.ticketmaster.com/event/3B00649CDC9E5BD5",
      expected_resolver_page_type: "exact_event",
      expected_resolver_execution_mode: "direct_execution",
      reason: "Short exact event URL; should remain exact event evidence if provider page renders.",
    },
    {
      id: "tmf-11",
      provider: "ticketmaster",
      intended_class: "ticketmaster_artist",
      url: "https://www.ticketmaster.ca/kacey-musgraves-tickets/artist/1668663",
      expected_resolver_page_type: "artist_or_performer",
      expected_resolver_execution_mode: "provider_start",
      reason: "Locale TLD artist page; verifies provider host handling across Ticketmaster CA.",
    },
    {
      id: "tmf-12",
      provider: "ticketmaster",
      intended_class: "ticketmaster_search",
      url: "https://www.ticketmaster.com/search?q=lil%20wayne",
      expected_resolver_page_type: "search_results",
      expected_resolver_execution_mode: "provider_start",
      reason: "Search page; must ask user choice and never click first result silently.",
    },
    {
      id: "tmf-13",
      provider: "ticketmaster",
      intended_class: "ticketmaster_search",
      url: "https://www.ticketmaster.com/search?q=disney%20on%20ice",
      expected_resolver_page_type: "search_results",
      expected_resolver_execution_mode: "provider_start",
      reason: "Search page for family tour; should extract candidates or return provider-degraded evidence.",
    },
    {
      id: "tmf-14",
      provider: "ticketmaster",
      intended_class: "ticketmaster_search",
      url: "https://www.ticketmaster.com/search?q=monster%20jam",
      expected_resolver_page_type: "search_results",
      expected_resolver_execution_mode: "provider_start",
      reason: "Search page for multi-city event; user must choose city/date.",
    },
    {
      id: "tmf-15",
      provider: "ticketmaster",
      intended_class: "ticketmaster_listing",
      url: "https://www.ticketmaster.com/category/concerts",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Category/listing shape; may degrade, but must not be exact event evidence.",
    },
    {
      id: "tmf-16",
      provider: "ticketmaster",
      intended_class: "ticketmaster_listing",
      url: "https://www.ticketmaster.com/category/sports",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Sports category/listing shape; useful for provider-degraded vs listing classification.",
    },
    {
      id: "tmf-17",
      provider: "ticketmaster",
      intended_class: "ticketmaster_listing",
      url: "https://www.ticketmaster.com/category/arts-theater",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Arts/theater category shape; should not produce exact event continuation.",
    },
    {
      id: "tmf-18",
      provider: "ticketmaster",
      intended_class: "ticketmaster_listing",
      url: "https://www.ticketmaster.com/category/family",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Family category shape; covers Disney/Monster Jam-like discovery surfaces.",
    },
    {
      id: "tmf-19",
      provider: "ticketmaster",
      intended_class: "ticketmaster_listing",
      url: "https://www.ticketmaster.com/madison-square-garden-tickets-new-york/venue/483329",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Venue page shape; should extract venue candidates or stop with provider evidence.",
    },
    {
      id: "tmf-20",
      provider: "ticketmaster",
      intended_class: "ticketmaster_listing",
      url: "https://www.ticketmaster.com/bridgestone-arena-tickets-nashville/venue/221676",
      expected_resolver_page_type: "listing",
      expected_resolver_execution_mode: "provider_start",
      reason: "Second venue page shape; useful for Nashville activity dogfood.",
    },
  ]);

export const TICKETMASTER_SKILL_FORGE_PLAN_COUNTS = {
  total: TICKETMASTER_SKILL_FORGE_PLAN.length,
  ticketmaster: TICKETMASTER_SKILL_FORGE_PLAN.length,
} as const;
